import React from 'react'
import Head from 'next/head'
import Image from 'next/image'

import styles from './Audio.module.scss'
import Hero from './Hero'
import Stats from './Stats'



export default function AudioComponent() {
  return (
    <div id={styles["container"]}>
        <Head>
            <title>Dylan King's Portfolio</title>
            <meta name="xk-portfolio" content="Generated by create next app" />
            <link rel="icon" href="favicon.ico?v=1.1"/>
        </Head>
        <main>
            <section id={styles["hero"]}>
                <Hero />
            </section>
            <section id={styles["stats"]}>
                <Stats />
            </section>
        </main>
    </div>
  )
}
