import '../styles/globals.css'
import Head from 'next/head'
import image from '../public/static/profilephotos/pp3.jpg'

function MyApp({ Component, pageProps }) {
  return (
    <>
    <Head>
        <title>xk-portfolio</title>
        <meta name="xk-portfolio" content="Generated by create next app" />
        <meta property="og:image" content={'/public/static/profilephotos/pp3.jpg'} />
        <link rel="icon" href="favicon.ico?v=1.1"/>
      </Head>
    {/* <nav className='navTemp'>
      <a href='/'><svg xmlns="http://www.w3.org/2000/svg" height="48" width="48"><path d="M8 42V18L24.1 6 40 18v24H28.3V27.75h-8.65V42Zm3-3h5.65V24.75H31.3V39H37V19.5L24.1 9.75 11 19.5Zm13-14.65Z"/></svg></a>
    </nav> */}

    <Component {...pageProps} />
    </>
  )
}

export default MyApp
