import '../styles/globals.css'
import Head from 'next/head'
import image2 from '../public/static/profilephotos/pp3.jpg'
import Image from 'next/image'

function MyApp({ Component, pageProps }) {
  return (
    <>
    <Head>
        <title>xk-portfolio</title>
        <meta name="xk-portfolio" content="Generated by create next app" />
        {/* <meta property="og:image" content={image2} /> */}
        <meta
          property="og:image"
          content="https://mj-gallery.com/d27fc3d5-0594-486c-995a-16223091ce83/grid_0.png"
        />
        <link rel="icon" href="favicon.ico?v=1.1"/>
      </Head>
      {/* <Image src={image2} objectFit='contain' /> */}

    {/* <nav className='navTemp'>
      <a href='/'><svg xmlns="http://www.w3.org/2000/svg" height="48" width="48"><path d="M8 42V18L24.1 6 40 18v24H28.3V27.75h-8.65V42Zm3-3h5.65V24.75H31.3V39H37V19.5L24.1 9.75 11 19.5Zm13-14.65Z"/></svg></a>
    </nav> */}

    <Component {...pageProps} />
    </>
  )
}

export default MyApp
