import Head from 'next/head'
import Image from 'next/image'
import StartScreen from '../Components/StartScreen/StartScreen'
// import styles from '../styles/StartScreen.module.scss'
import imageShare from '../public/static/profilephotos/pp3.jpg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>2xk-portfolio</title>
        <meta name="22xk-portfolio" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico?v=1.1"/>
        <meta
          property="og:image"
          content={imageShare}
        />
      </Head>

      <main>
        <StartScreen />
      </main>

      <footer>
      </footer>
    </div>
  )
}
